#!/bin/bash
# Copyright (c) Paul Tagliamonte, 2012, Expat.

while read x; do
    if [ -e pids/$x.pid ]; then
        PID=$(ps -ef | grep $(cat pids/$x.pid) | grep -v grep | awk '{print $2}')
        echo -n "$x  - "
        if [ "x$PID" == "x" ]; then
            echo "[ [31mFail[0m ]"
        else
            echo "[  [33mok[0m  ]"
        fi
    else
        echo "$x - Not running."
    fi
done < apps
